### ISSUE TITLE
Bug: Cannot access firebase use coffee-and-code-philly-website project through Firebase CLI

### ISSUE THREAD

**Issue by derekmeegan** [Coffee-Code-Philly-Accelerator/coffee_and_code_philly_dot_com#18]
I followed the setup directions but ran into the following error when trying to access the project
<img width="851" alt="Screenshot 2024-07-11 at 2 53 58 PM" src="https://github.com/Coffee-Code-Philly-Accelerator/coffee_and_code_philly_dot_com/assets/75138022/4935488d-73da-48f9-914e-c56b35a567c4">

**Comment by MosesSupposes** [comment]
Hm, were you able to successfully authenticate with `firebase login`?

**Comment by derekmeegan** [comment]
Updated Read.me with instructions for installing firebase packages and selecting project with built in selector command
