### ISSUE TITLE
Disable broken links

### ISSUE THREAD

**Issue by MosesSupposes** [Coffee-Code-Philly-Accelerator/coffee_and_code_philly_dot_com#43]
Currently, only half the links on the main navigation bar route correctly. The other half: `/join-us`, `/projects`, and `/events` return a 404 when requested. We should remove or at least disable these links until their respective pages are implemented and readily accessible.

**Comment by derekmeegan** [comment]
This was fixed when i fixed the merge conflict in PR #40
